#pragma once

#define ERROR_OK 0
#define ERROR_DONT_USE_THIS_SHIT 1
#define ERROR_PROC_OPEN 2
#define ERROR_REMOTE_ALLOC 3
#define ERROR_REMOTE_WRITE 4
#define ERROR_REMOTE_EXEC 5
#define ERROR_LOAD_LIBRARY 6
#define ERROR_NO_EXPORT 7
#define ERROR_FAILED_ELEVATION 8
#define ERROR_INVALID_ARGUMENTS 9
#define ERROR_NO_ACCESS 10
#define ERROR_ENUMERATE_MODULES 11
#define ERROR_MODULE_NOT_FOUND 12
#define ERROR_EXEC_CHAINED_COMMAND 13
#define ERROR_PROC_EXITED 14